from __future__ import annotations

from dataclasses import dataclass

# Generated by tools/generate_sa_runtime_collision_module.py from
# docs/derived_collision_tables_all/SAM1_runtime_collision_calls.json.
#
# Only the EXE parser contexts that correspond to actual SAM?03.GFX mission map
# bytes are included here:
#   - CS:3a59..3a8f  special low-byte object parser
#   - CS:66f9..68a7  main SAMLEV one-byte row parser
# The earlier CS:2e20 ASCII-like parser is intentionally excluded because it is
# a different context and gives wrong answers for mission-map bytes such as 0x70.
#
# Pass 5 correction: coordinates are column-major in the EXE runtime buffer.
# The setter's 0xC8 stride is an X-column stride (25 padded Y cells * 8 bytes),
# so bp+14 is logical X and bp+12 is logical Y.


@dataclass(frozen=True)
class RuntimeCellWrite:
    dx: int
    dy: int
    c6: int
    c8: int
    cA: int
    body_solid: bool
    foot_solid: bool
    context: str
    requires_bg_row: bool


RUNTIME_CELL_WRITES: dict[int, tuple[RuntimeCellWrite, ...]] = {
    0x01: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x026B, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x02: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x00A1, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x03: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x00A2, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x04: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x009B, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x05: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x009C, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x009D, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x06: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x009E, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x07: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x00AE, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x08: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x00B5, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x00B6, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x0B: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x00B2, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x0C: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x00B9, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x00BA, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x0E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02DD, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x0F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02DE, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x10: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02DF, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x11: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02E1, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x12: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02E5, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x13: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02E7, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x14: (
        RuntimeCellWrite(dx=0, dy=-1, c6=0x0002, c8=0x02E9, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02ED, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x15: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02EA, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x16: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02EE, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x17: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02A5, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x18: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02A6, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x19: (
        RuntimeCellWrite(dx=0, dy=-1, c6=0x0002, c8=0x00FB, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x00FF, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x1B: (
        RuntimeCellWrite(dx=-1, dy=-1, c6=0x0002, c8=0x00FC, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=-1, c6=0x0002, c8=0x00FD, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x0100, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0101, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x1C: (
        RuntimeCellWrite(dx=0, dy=-1, c6=0x0002, c8=0x00FE, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0102, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x1E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0008, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x1F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x00A6, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x20: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x21: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02EF, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x23: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x24: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x25: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x0000, cA=0x01C4, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01C5, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x26: (
        RuntimeCellWrite(dx=-1, dy=-1, c6=0x01C7, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=-1, c6=0x01C8, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=-1, dy=0, c6=0x01CB, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x01CC, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x28: (
        RuntimeCellWrite(dx=-1, dy=-1, c6=0x01C9, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=-1, c6=0x01CA, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=-1, dy=0, c6=0x01CD, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x01CE, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x29: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01CF, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x2A: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01D3, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x2B: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01A5, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x2C: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01A6, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x2D: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01A7, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x2E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01A8, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x2F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01A9, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x30: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x31: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0001, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x32: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0003, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x33: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0004, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x34: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01AA, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x35: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0005, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x36: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0006, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x37: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0007, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x38: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x39: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x3A: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01D2, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x3B: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01AC, body_solid=True, foot_solid=False, context='special_low', requires_bg_row=False),
        RuntimeCellWrite(dx=0, dy=-1, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01AB, body_solid=True, foot_solid=False, context='special_low', requires_bg_row=False),
    ),
    0x3C: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01E7, body_solid=True, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x3D: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01EB, body_solid=True, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x3E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01B1, body_solid=True, foot_solid=False, context='special_low', requires_bg_row=True),
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01B2, body_solid=True, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x3F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x40: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x012E, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x41: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x42: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02F1, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x43: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02F3, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x44: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0265, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x45: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0000, cA=0x0266, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x46: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02F4, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x47: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x48: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01D4, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x49: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x4A: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02F5, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x4B: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x025E, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x4C: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0315, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x4D: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0270, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x4E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0139, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x4F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0267, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x50: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0130, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x51: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x01D1, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x52: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x01D0, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x53: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0316, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x54: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x013C, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x55: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0268, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x56: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x57: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x026A, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x58: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x59: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x5A: (
        RuntimeCellWrite(dx=-1, dy=-1, c6=0x0002, c8=0x031B, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=-1, c6=0x0002, c8=0x031C, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x031F, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0320, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x5B: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x5C: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x026C, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x5D: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0275, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x5E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x013A, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x5F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x60: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x01F3, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x61: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x01F4, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x62: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x63: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x64: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0276, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x65: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x66: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0277, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x67: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x68: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0278, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x69: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x01B9, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x6A: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x01BA, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x6B: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x01BB, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x6C: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x01BC, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x6D: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x6E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x6F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x01A1, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x70: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x009F, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x00A0, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x71: (
        RuntimeCellWrite(dx=0, dy=-1, c6=0x0002, c8=0x0000, cA=0x0279, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x027D, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x72: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x025F, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x73: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x012D, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x74: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x027B, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x75: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x76: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x77: (
        RuntimeCellWrite(dx=0, dy=-1, c6=0x0002, c8=0x0000, cA=0x00B3, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x00B7, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x78: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x79: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x013E, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x013F, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x7A: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x013D, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x7C: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x01A3, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x7E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x01A4, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x7F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0x80: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0259, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x81: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x025A, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x82: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x025B, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x83: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x025C, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x84: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x025D, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x85: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x00DD, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x00DE, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x0000, cA=0x00DF, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x00E0, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x86: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x00E5, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x0000, cA=0x00E6, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x00E7, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x87: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0143, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0144, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x88: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0159, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x89: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x015A, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x8A: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x015B, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x8B: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x681A, c8=0x00A3, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x00A4, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x8C: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x026D, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x8D: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x026E, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x8E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x026F, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x8F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x028B, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x90: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x028C, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x91: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x028D, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x92: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x028E, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0x93: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x028F, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x94: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0290, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x95: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x01C1, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x96: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0292, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x97: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0293, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x98: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0294, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x99: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0295, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x9A: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x681A, c8=0x00A6, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x00A5, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x9B: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0297, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x9C: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0298, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x9D: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0299, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x9E: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x029A, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0x9F: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0317, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xA0: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0318, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xA1: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0319, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xA2: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x015C, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xA3: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x029F, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xA4: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02A0, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xA5: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02A1, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xA6: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02A2, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xA7: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xA8: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x00AF, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xA9: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x00B0, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xAA: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x00B1, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xAB: (
        RuntimeCellWrite(dx=0, dy=-1, c6=0x00C2, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x00C6, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xAC: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x00C5, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xAD: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x00C1, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xAE: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0xAF: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x015D, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB0: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02AC, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB1: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02AD, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB2: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02AE, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB3: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02AF, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB4: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02B0, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB5: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02B1, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB6: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02A9, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB7: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02B3, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB8: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02B4, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xB9: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02B5, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xBA: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x02B2, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x02B6, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xBB: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02B7, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xBC: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02BA, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xBD: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02B8, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xBE: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02B9, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xBF: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x02A7, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x02A8, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xC0: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x02BB, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x02BC, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xC1: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02BD, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xC2: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02BE, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xC3: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02BF, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xC4: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02C0, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xC5: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02C1, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xC6: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02C2, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xC7: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02C3, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xC8: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02C4, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xC9: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02C5, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xCA: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02C6, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xCB: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0000, cA=0x02C7, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xCC: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0000, cA=0x02C8, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xCD: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0000, cA=0x02C9, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xCE: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02CA, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xCF: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02CB, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xD0: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02CC, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xD1: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xD2: (
        RuntimeCellWrite(dx=-1, dy=-1, c6=0x00BF, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=-1, c6=0x00C0, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=-1, dy=0, c6=0x00C3, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x00C4, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xD3: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0000, cA=0xFFFF, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xD4: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='special_low', requires_bg_row=True),
    ),
    0xD5: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02D1, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xD6: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02D2, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xD7: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02D3, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xD8: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x010C, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x010D, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xD9: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02D5, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xDA: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02D6, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xDB: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02D7, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xDC: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02D8, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xDD: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x02D9, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xDE: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x02DA, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xDF: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x00C9, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xE0: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x00CA, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xE1: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x00CB, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xE2: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x00CD, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xE3: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x00CE, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xE4: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x00CF, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xE5: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x02F6, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xE6: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02F7, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xE7: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02F8, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xE8: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02F9, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xE9: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02FA, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xEA: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02FB, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xEB: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02FC, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xEC: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0000, cA=0x02FD, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xED: (
        RuntimeCellWrite(dx=-1, dy=0, c6=0x00C7, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x00C8, c8=0x0000, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xEE: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x0108, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=-1, dy=0, c6=0x0002, c8=0x0109, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x010A, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
    ),
    0xEF: (
        RuntimeCellWrite(dx=0, dy=-1, c6=0x0002, c8=0x0107, cA=0x0000, body_solid=False, foot_solid=True, context='mission_main', requires_bg_row=True),
        RuntimeCellWrite(dx=0, dy=0, c6=0x0002, c8=0x010B, cA=0x0000, body_solid=False, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xF1: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0307, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xF2: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0308, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xF3: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0309, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xF4: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x030A, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xF5: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x030B, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xF6: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x030C, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xF7: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x030D, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xF8: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x030E, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xF9: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x030F, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xFA: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0310, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xFB: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0311, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xFC: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0312, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xFD: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x681A, c8=0x0313, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
    0xFE: (
        RuntimeCellWrite(dx=0, dy=0, c6=0x0314, c8=0x0000, cA=0x0000, body_solid=True, foot_solid=False, context='mission_main', requires_bg_row=True),
    ),
}

BODY_SOLID_CODES = frozenset({
    0x1F, 0x26, 0x28, 0x2C, 0x2E, 0x31, 0x32, 0x33, 0x34, 0x3B, 0x3C, 0x3D,
    0x3E, 0x43, 0x46, 0x4A, 0x4C, 0x61, 0x6B, 0x6F, 0x71, 0x77, 0x8B, 0x8F,
    0x90, 0x91, 0x93, 0x94, 0x9A, 0x9F, 0xA0, 0xA1, 0xC1, 0xC2, 0xC3, 0xC4,
    0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xE5, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6,
    0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE,
})

FOOT_SOLID_CODES = frozenset({
    0x05, 0x08, 0x0B, 0x0C, 0x19, 0x1B, 0x1C, 0x42, 0x45, 0x49, 0x5A, 0x6A,
    0x6C, 0x79, 0x85, 0x86, 0x87, 0x92, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xAB,
    0xAD, 0xBA, 0xBF, 0xC0, 0xCB, 0xCC, 0xCD, 0xD2, 0xD5, 0xD6, 0xD7, 0xD8,
    0xDA, 0xDB, 0xDC, 0xDE, 0xDF, 0xE0, 0xE1, 0xED, 0xEE, 0xEF,
})

KNOWN_RUNTIME_CODES = frozenset({
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x0B, 0x0C, 0x0E, 0x0F,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1B, 0x1C,
    0x1E, 0x1F, 0x20, 0x21, 0x23, 0x24, 0x25, 0x26, 0x28, 0x29, 0x2A, 0x2B,
    0x2C, 0x2D, 0x2E, 0x2F, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37,
    0x38, 0x39, 0x3A, 0x3B, 0x3C, 0x3D, 0x3E, 0x3F, 0x40, 0x41, 0x42, 0x43,
    0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x4B, 0x4C, 0x4D, 0x4E, 0x4F,
    0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A, 0x5B,
    0x5C, 0x5D, 0x5E, 0x5F, 0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67,
    0x68, 0x69, 0x6A, 0x6B, 0x6C, 0x6D, 0x6E, 0x6F, 0x70, 0x71, 0x72, 0x73,
    0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A, 0x7C, 0x7E, 0x7F, 0x80, 0x81,
    0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D,
    0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99,
    0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5,
    0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1,
    0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD,
    0xBE, 0xBF, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9,
    0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5,
    0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xE0, 0xE1,
    0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED,
    0xEE, 0xEF, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA,
    0xFB, 0xFC, 0xFD, 0xFE,
})


def runtime_cell_writes_for_code(code: int) -> tuple[RuntimeCellWrite, ...]:
    return RUNTIME_CELL_WRITES.get(code, ())


def code_has_body_solid(code: int) -> bool:
    return code in BODY_SOLID_CODES


def code_has_foot_solid(code: int) -> bool:
    return code in FOOT_SOLID_CODES


def code_known_to_exe_collision_table(code: int) -> bool:
    return code in KNOWN_RUNTIME_CODES
