from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "docs" / "derived_collision_tables_all" / "SAM1_runtime_collision_calls.json"
OUT = ROOT / "openagent" / "exe_runtime_collision.py"

RELEVANT_RANGES = ((0x3A59, 0x3A8F, "special_low"), (0x66F9, 0x68A7, "mission_main"))


def context_for(offset: int) -> str | None:
    for lo, hi, name in RELEVANT_RANGES:
        if lo <= offset <= hi:
            return name
    return None


def rel(expr: str, axis: str) -> int:
    # Important correction from pass 5:
    # The runtime collision buffer is column-major: the setter multiplies bp+14
    # by 0xC8 (= 25 cells * 8 bytes) and bp+12 by 8.  0xC8 is therefore the
    # stride between X columns, not between screen rows.  The extractor field
    # named "y" is the first setter argument (bp+14) and is the logical X
    # coordinate; the field named "x" is the second setter argument (bp+12) and
    # is the logical Y coordinate.
    expr = expr.replace("bp+c", "bp+0c").replace("bp+e", "bp+0e")
    bases = {"x": ("bp-2c", "bp+0e"), "y": ("bp+0a", "bp+0c")}[axis]
    for base in bases:
        if expr == base:
            return 0
        if expr == base + "-1":
            return -1
        if expr == base + "+1":
            return 1
    raise ValueError(f"cannot convert {axis} expression {expr!r} to relative offset")


def to_int(v):
    return v if isinstance(v, int) else int(v)


def main() -> None:
    arr = json.loads(SRC.read_text())
    grouped: dict[int, list[dict]] = {}
    for e in arr:
        ctx = context_for(int(e["token_offset"]))
        if ctx is None:
            continue
        code = int(e["token_second"])
        w = {
            # See rel(): the CSV column names are historical/extractor names,
            # not logical axes.  First setter coordinate => dx, second => dy.
            "dx": rel(e["y"], "x"),
            "dy": rel(e["x"], "y"),
            "c6": int(str(e["internal_code"]), 16),
            "c8": int(str(e["layer_b"]), 16),
            "ca": int(str(e["layer_c"]), 16),
            "body": bool(to_int(e["body_solid"])),
            "foot": bool(to_int(e["foot_solid"])),
            "ctx": ctx,
            "requires_bg_row": str(e["unknown"]) != "0",
        }
        grouped.setdefault(code, []).append(w)

    body = sorted(c for c, ws in grouped.items() if any(w["body"] for w in ws))
    foot = sorted(c for c, ws in grouped.items() if any(w["foot"] for w in ws))
    known = sorted(grouped)

    def fmt_set(values):
        if not values:
            return "frozenset()"
        lines = []
        for i in range(0, len(values), 12):
            lines.append("    " + ", ".join(f"0x{x:02X}" for x in values[i:i+12]) + ",")
        return "frozenset({\n" + "\n".join(lines) + "\n})"

    def fmt_writes():
        lines = ["{"]
        for code in known:
            lines.append(f"    0x{code:02X}: (")
            for w in grouped[code]:
                lines.append(
                    "        RuntimeCellWrite("
                    f"dx={w['dx']}, dy={w['dy']}, c6=0x{w['c6']:04X}, c8=0x{w['c8']:04X}, cA=0x{w['ca']:04X}, "
                    f"body_solid={w['body']}, foot_solid={w['foot']}, context={w['ctx']!r}, requires_bg_row={w['requires_bg_row']}),"
                )
            lines.append("    ),")
        lines.append("}")
        return "\n".join(lines)

    text = f'''from __future__ import annotations

from dataclasses import dataclass

# Generated by tools/generate_sa_runtime_collision_module.py from
# docs/derived_collision_tables_all/SAM1_runtime_collision_calls.json.
#
# Only the EXE parser contexts that correspond to actual SAM?03.GFX mission map
# bytes are included here:
#   - CS:3a59..3a8f  special low-byte object parser
#   - CS:66f9..68a7  main SAMLEV one-byte row parser
# The earlier CS:2e20 ASCII-like parser is intentionally excluded because it is
# a different context and gives wrong answers for mission-map bytes such as 0x70.
#
# Pass 5 correction: coordinates are column-major in the EXE runtime buffer.
# The setter's 0xC8 stride is an X-column stride (25 padded Y cells * 8 bytes),
# so bp+14 is logical X and bp+12 is logical Y.


@dataclass(frozen=True)
class RuntimeCellWrite:
    dx: int
    dy: int
    c6: int
    c8: int
    cA: int
    body_solid: bool
    foot_solid: bool
    context: str
    requires_bg_row: bool


RUNTIME_CELL_WRITES: dict[int, tuple[RuntimeCellWrite, ...]] = {fmt_writes()}

BODY_SOLID_CODES = {fmt_set(body)}

FOOT_SOLID_CODES = {fmt_set(foot)}

KNOWN_RUNTIME_CODES = {fmt_set(known)}


def runtime_cell_writes_for_code(code: int) -> tuple[RuntimeCellWrite, ...]:
    return RUNTIME_CELL_WRITES.get(code, ())


def code_has_body_solid(code: int) -> bool:
    return code in BODY_SOLID_CODES


def code_has_foot_solid(code: int) -> bool:
    return code in FOOT_SOLID_CODES


def code_known_to_exe_collision_table(code: int) -> bool:
    return code in KNOWN_RUNTIME_CODES
'''
    OUT.write_text(text)
    print(f"wrote {OUT}")
    print(f"{len(known)} codes, {sum(len(v) for v in grouped.values())} runtime writes")


if __name__ == "__main__":
    main()
